const UNSPLASH_HOST = "images.unsplash.com";
const UNSPLASH_SRCSET_WIDTHS = [640, 960, 1280, 1920] as const;

const OS_STORAGE_HOST = "os.presentail.com";
const OS_STORAGE_PATH_PREFIX = "/api/storage/";
const OS_SRCSET_WIDTHS = [400, 800, 1200] as const;

/**
 * Given an Unsplash image URL that already contains a `w=` parameter, returns
 * `{ srcset, sizes }` strings suitable for a responsive `<img>` hero banner:
 *
 * - `srcset`: one entry per width in `UNSPLASH_SRCSET_WIDTHS`, generated by replacing
 *   the existing `w=` value.
 * - `sizes`: `(max-width: 1280px) 100vw, 1280px` — matches the hero layout
 *   where the banner spans the full viewport up to the 1280 px content cap.
 *
 * Returns `null` for any URL whose host is not `images.unsplash.com` so
 * non-Unsplash banner sources are always passed through unchanged.
 */
export function buildUnsplashSrcset(url: string): { srcset: string; sizes: string } | null {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }

  if (parsed.hostname !== UNSPLASH_HOST) return null;
  if (!parsed.searchParams.has("w")) return null;

  const srcset = UNSPLASH_SRCSET_WIDTHS.map((w) => {
    const u = new URL(url);
    u.searchParams.set("w", String(w));
    return `${u.toString()} ${w}w`;
  }).join(", ");

  const sizes = "(max-width: 1280px) 100vw, 1280px";

  return { srcset, sizes };
}

/**
 * Returns true when the given URL points to an OS storage image that can be
 * served via the `/api/img/proxy` endpoint.
 */
export function isOsStorageUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    return parsed.hostname === OS_STORAGE_HOST && parsed.pathname.startsWith(OS_STORAGE_PATH_PREFIX);
  } catch {
    return false;
  }
}

/**
 * Builds the proxy URL for a single OS storage image at the given width.
 * Returns the raw URL unchanged when it is not an OS storage path.
 */
export function buildOsProxyUrl(url: string, width: number, format: "webp" | "jpeg" = "webp"): string {
  if (!isOsStorageUrl(url)) return url;
  return `/api/img/proxy?url=${encodeURIComponent(url)}&w=${width}&f=${format}`;
}

/**
 * Given an OS storage image URL, returns `{ srcset, sizes, src }` for a
 * responsive `<img>` element:
 *
 * - `srcset`: three entries at 400w, 800w, 1200w pointing at `/api/img/proxy`.
 * - `sizes`: a sensible default hint covering mobile cards through desktop hero.
 * - `src`: the 800w proxy URL so the browser gets WebP even when srcset is not
 *   supported (old browsers, RSS readers, etc.).
 *
 * Returns `null` for any URL that is not an OS storage path so callers can
 * fall back to the raw URL unchanged.
 */
export function buildOsImageSrcset(
  url: string,
  sizes = "(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 800px",
): { srcset: string; sizes: string; src: string } | null {
  if (!isOsStorageUrl(url)) return null;

  const srcset = OS_SRCSET_WIDTHS.map((w) => `${buildOsProxyUrl(url, w)} ${w}w`).join(", ");
  const src = buildOsProxyUrl(url, 800);

  return { srcset, sizes, src };
}
