const UNSPLASH_HOST = "images.unsplash.com";
const UNSPLASH_SRCSET_WIDTHS = [640, 960, 1280, 1920] as const;

const OS_STORAGE_HOST = "os.presentail.com";
const OS_STORAGE_PATH_PREFIX = "/api/storage/public-objects/";
const OS_SRCSET_WIDTHS = [400, 800, 1200] as const;

// Catalog proxy URL path prefixes (relative, served by the API server).
const CATALOG_IMAGE_PREFIXES = [
  "/api/catalog/occasion-image/",
  "/api/catalog/category-image/",
  "/api/catalog/brand-image/",
] as const;

// Srcset widths for catalog card images. At 144 CSS px the 2× retina entry
// (288) covers HiDPI; 480 covers the occasional larger hero-style card.
const CATALOG_SRCSET_WIDTHS = [144, 288, 480] as const;

// Srcset widths for catalog hero images (brand cover, occasion/category banner).
// 800 covers narrow viewports (≤768 px); 1200 covers desktop up to the 1280 px
// content cap; 1600 serves 2× retina desktop displays.
const CATALOG_HERO_SRCSET_WIDTHS = [800, 1200, 1600] as const;

function parseOsStorageUrl(url: string): URL | null {
  try {
    const parsed = new URL(url.replace(/%(?![0-9a-fA-F]{2})/g, "%25"));
    if (
      parsed.protocol !== "https:" ||
      parsed.hostname !== OS_STORAGE_HOST ||
      parsed.username ||
      parsed.password ||
      !parsed.pathname.startsWith(OS_STORAGE_PATH_PREFIX) ||
      parsed.pathname === OS_STORAGE_PATH_PREFIX
    ) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Given an Unsplash image URL that already contains a `w=` parameter, returns
 * `{ srcset, sizes }` strings suitable for a responsive `<img>` hero banner:
 *
 * - `srcset`: one entry per width in `UNSPLASH_SRCSET_WIDTHS`, generated by replacing
 *   the existing `w=` value.
 * - `sizes`: `(max-width: 1280px) 100vw, 1280px` — matches the hero layout
 *   where the banner spans the full viewport up to the 1280 px content cap.
 *
 * Returns `null` for any URL whose host is not `images.unsplash.com` so
 * non-Unsplash banner sources are always passed through unchanged.
 */
export function buildUnsplashSrcset(url: string): { srcset: string; sizes: string } | null {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }

  if (parsed.hostname !== UNSPLASH_HOST) return null;
  if (!parsed.searchParams.has("w")) return null;

  const srcset = UNSPLASH_SRCSET_WIDTHS.map((w) => {
    const u = new URL(url);
    u.searchParams.set("w", String(w));
    return `${u.toString()} ${w}w`;
  }).join(", ");

  const sizes = "(max-width: 1280px) 100vw, 1280px";

  return { srcset, sizes };
}

/**
 * Builds a `srcset` string for a locally-hosted image that has pre-generated
 * width variants following the `<base>-<width>.webp` naming convention
 * (e.g. `/blog/post.webp` → `/blog/post-480.webp`, `/blog/post-768.webp`).
 *
 * The variant widths are emitted first, then the original `url` at its
 * intrinsic `intrinsicWidth` as the largest descriptor so the browser can pick
 * the full-resolution file on high-DPI displays. Widths greater than or equal
 * to `intrinsicWidth` are skipped to avoid up-scaled (and pointlessly larger)
 * descriptors.
 *
 * The original `url` must stay the `<img src>` so non-srcset consumers (old
 * browsers, link-preview crawlers) and the canonical og:image are unaffected.
 */
export function buildSrcSet(url: string, variantWidths: number[], intrinsicWidth: number): string {
  const base = url.replace(/\.webp$/i, "");
  const entries = variantWidths
    .filter((w) => w < intrinsicWidth)
    .map((w) => `${base}-${w}.webp ${w}w`);
  entries.push(`${url} ${intrinsicWidth}w`);
  return entries.join(", ");
}

/**
 * Returns true when the given URL points to an OS storage image that can be
 * served via the `/api/img/proxy` endpoint.
 */
export function isOsStorageUrl(url: string): boolean {
  return parseOsStorageUrl(url) !== null;
}

/**
 * Return the canonical URL string used as the nested `url` query parameter.
 * URL serialisation encodes spaces and Unicode once; encodeURIComponent then
 * safely nests that URL, including literal +, %, &, and its own query params.
 */
export function canonicalizeOsStorageUrl(url: string): string | null {
  return parseOsStorageUrl(url)?.toString() ?? null;
}

/**
 * Returns true when the given URL is a relative catalog image proxy path
 * (one of the two `/api/catalog/*-image/…` endpoints).
 */
export function isCatalogProxyUrl(url: string): boolean {
  return CATALOG_IMAGE_PREFIXES.some((prefix) => url.startsWith(prefix));
}

/**
 * Builds the proxy URL for a single OS storage image at the given width.
 * Returns the raw URL unchanged when it is not an OS storage path.
 */
export function buildOsProxyUrl(url: string, width: number, format: "webp" | "jpeg" = "webp"): string {
  if (url.startsWith("/api/img/proxy?")) {
    const params = new URLSearchParams(url.slice(url.indexOf("?") + 1));
    if (!params.has("url")) return url;
    params.set("w", String(width));
    params.set("f", format);
    return `/api/img/proxy?${params.toString()}`;
  }
  const canonical = canonicalizeOsStorageUrl(url);
  if (!canonical) return url;
  return `/api/img/proxy?url=${encodeURIComponent(canonical)}&w=${width}&f=${format}`;
}

/**
 * Given an OS storage image URL, returns `{ srcset, sizes, src }` for a
 * responsive `<img>` element:
 *
 * - `srcset`: three entries at 400w, 800w, 1200w pointing at `/api/img/proxy`.
 * - `sizes`: a sensible default hint covering mobile cards through desktop hero.
 * - `src`: the 800w proxy URL so the browser gets WebP even when srcset is not
 *   supported (old browsers, RSS readers, etc.).
 *
 * Returns `null` for any URL that is not an OS storage path so callers can
 * fall back to the raw URL unchanged.
 */
export function buildOsImageSrcset(
  url: string,
  sizes = "(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 800px",
): { srcset: string; sizes: string; src: string } | null {
  if (!isOsStorageUrl(url) && !url.startsWith("/api/img/proxy?")) return null;

  const srcset = OS_SRCSET_WIDTHS.map((w) => `${buildOsProxyUrl(url, w)} ${w}w`).join(", ");
  const src = buildOsProxyUrl(url, 800);

  return { srcset, sizes, src };
}

/**
 * Given a catalog image proxy URL (`/api/catalog/occasion-image/…` or
 * `/api/catalog/brand-image/…`), returns `{ srcset, sizes, src }` for a
 * responsive `<img>` element:
 *
 * - `srcset`: three entries at 144w, 288w, 480w appending `?w=…&f=webp`.
 * - `sizes`: caller-supplied or the default card hint.
 * - `src`: the 288w proxy URL (decent retina fallback for non-srcset consumers).
 *
 * Returns `null` for any URL that is not a recognized catalog proxy path.
 */
export function buildCatalogImageSrcset(
  url: string,
  sizes = "(max-width: 768px) 25vw, 300px",
): { srcset: string; sizes: string; src: string } | null {
  if (!isCatalogProxyUrl(url)) return null;

  // Append (or replace) w and f params. The base URL may already contain a
  // trailing slash — we append query params directly.
  const withVariant = (width: number) => {
    const [path, query = ""] = url.split("?", 2);
    const params = new URLSearchParams(query);
    params.set("w", String(width));
    params.set("f", "webp");
    return `${path}?${params.toString()}`;
  };
  const srcset = CATALOG_SRCSET_WIDTHS.map((w) => `${withVariant(w)} ${w}w`).join(", ");
  const src = withVariant(288);

  return { srcset, sizes, src };
}

/**
 * Given a catalog image proxy URL, returns `{ srcset, sizes, src }` optimised
 * for a full-width page hero (brand cover, occasion/category banner):
 *
 * - `srcset`: three entries at 800w, 1200w, 1600w — covers mobile through
 *   2× retina desktop without serving the un-resized original.
 * - `sizes`: `(max-width: 1280px) 100vw, 1280px` — matches the hero layout
 *   where the banner spans the full viewport up to the 1280 px content cap.
 * - `src`: the 1200w proxy URL as a sensible non-srcset fallback.
 *
 * Returns `null` for any URL that is not a recognized catalog proxy path so
 * callers can fall back to the raw URL or a static asset unchanged.
 */
export function buildCatalogHeroImageSrcset(
  url: string,
  sizes = "(max-width: 1280px) 100vw, 1280px",
): { srcset: string; sizes: string; src: string } | null {
  if (!isCatalogProxyUrl(url)) return null;

  const withVariant = (width: number) => {
    const [path, query = ""] = url.split("?", 2);
    const params = new URLSearchParams(query);
    params.set("w", String(width));
    params.set("f", "webp");
    return `${path}?${params.toString()}`;
  };
  const srcset = CATALOG_HERO_SRCSET_WIDTHS.map((w) => `${withVariant(w)} ${w}w`).join(", ");
  const src = withVariant(1200);

  return { srcset, sizes, src };
}

/**
 * Default sizes hint for the first-card hero in the CategoriesGrid layout.
 * Kept here so the component and tests share a single source of truth, and a
 * future layout change only needs to be updated in one place.
 */
export const CATEGORY_CARD_HERO_SIZES = "(max-width: 768px) 25vw, 600px";

/**
 * Resolves the srcset result for the first (hero) category card in
 * CategoriesGrid. Branches on URL type:
 *
 * - catalog proxy path  → `buildCatalogHeroImageSrcset` (800w/1200w/1600w WebP)
 * - OS storage URL      → `buildOsImageSrcset` (400w/800w/1200w via img proxy)
 * - static asset / other → `null` (no srcset; raw `src` is used as-is)
 *
 * A sizes override can be passed when the layout changes so callers don't have
 * to duplicate the branching logic.
 */
export function buildCategoryHeroSrcset(
  imgSrc: string,
  sizes = CATEGORY_CARD_HERO_SIZES,
): { srcset: string; sizes: string; src: string } | null {
  if (isCatalogProxyUrl(imgSrc)) {
    return buildCatalogHeroImageSrcset(imgSrc, sizes);
  }
  return buildOsImageSrcset(imgSrc, sizes);
}

/**
 * Default sizes hint for the brand detail hero banner.
 * Kept here so BrandDetail.tsx and its tests share a single source of truth,
 * and a future layout change only needs to be updated in one place.
 *
 * The brand hero spans the full content width up to the 1280 px content cap.
 */
export const BRAND_HERO_SIZES = "(max-width: 1280px) 100vw, 1280px";

/**
 * Resolves the srcset result for the brand detail page hero banner.
 * Branches on URL type:
 *
 * - catalog proxy path  → `buildCatalogHeroImageSrcset` (800w/1200w/1600w WebP)
 * - OS storage URL      → `buildOsImageSrcset` (400w/800w/1200w via img proxy)
 * - static asset / other → `null` (no srcset; raw `src` is used as-is)
 *
 * A sizes override can be passed when the layout changes so callers don't have
 * to duplicate the branching logic.
 */
export function buildBrandHeroSrcset(
  imgSrc: string,
  sizes = BRAND_HERO_SIZES,
): { srcset: string; sizes: string; src: string } | null {
  if (isCatalogProxyUrl(imgSrc)) {
    return buildCatalogHeroImageSrcset(imgSrc, sizes);
  }
  if (isOsStorageUrl(imgSrc)) {
    return buildOsImageSrcset(imgSrc, sizes);
  }
  return null;
}

