uploads = []
outputs = []

[[generated]]
id = "aQWaGAvLzz0O-GA-SQqgl"
uri = "file://artifacts/presentail/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wP-gcT43_-EtyIYRH1Iig"
uri = "file://artifacts/presentail/assets/images/hero-flowers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ldJIhkzNEOyLd9xyJCwAt"
uri = "file://artifacts/presentail/assets/images/hero-gifts.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-lQPgoyeGGlROm1bmilRe"
uri = "file://artifacts/presentail/assets/images/collection-vases.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WomciUH5SjBThYsGaBpWj"
uri = "file://artifacts/presentail/assets/images/best-roses.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VFVuKg4qVlR-dSZyD4r5b"
uri = "file://artifacts/presentail/assets/images/best-birthday.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WcdvuIzO4V6zF5m6j2SUs"
uri = "file://artifacts/presentail/assets/images/best-orchid.png"
type = "image"
title = "generated_image"

[[generated]]
id = "F6Nd6SwVvA6WYH1cQFxcN"
uri = "file://artifacts/presentail/assets/images/best-mixed.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nZBZiLtr7BQX0dqb1QHa8"
uri = "file://artifacts/presentail-web/src/assets/hero.png"
type = "image"
title = "Hero banner flowers"

[[generated]]
id = "U3dZiEOTmNucuWdulr1SJ"
uri = "file://artifacts/presentail-web/src/assets/category-bouquets.png"
type = "image"
title = "Hand Bouquets category"

[[generated]]
id = "lWz643PelSSnCRPjnzwhD"
uri = "file://artifacts/presentail-web/src/assets/category-boxes.png"
type = "image"
title = "Flower Boxes category"

[[generated]]
id = "gylZGZw7_mpLwvXf2eHnZ"
uri = "file://artifacts/presentail-web/src/assets/category-plants.png"
type = "image"
title = "Plants category"

[[generated]]
id = "OuS-UYB51U1h9SB7YP32o"
uri = "file://artifacts/presentail-web/src/assets/category-cakes.png"
type = "image"
title = "Cakes category"

[[generated]]
id = "cc37P6NpW-LeOeItF_J6L"
uri = "file://artifacts/presentail-web/src/assets/category-chocolate.png"
type = "image"
title = "Chocolate category"

[[generated]]
id = "7t7xd098g-e_eHTf7ljMy"
uri = "file://artifacts/presentail/assets/images/hero-slide1.png"
type = "image"
title = "teal bg pink bouquet"

[[generated]]
id = "ALup9kADuaWKg6I0xWU-w"
uri = "file://artifacts/presentail/assets/images/hero-slide2.png"
type = "image"
title = "teal bg roses hatbox v3"

[[generated]]
id = "l1Ynim1_iJybUivOukgwM"
uri = "file://artifacts/presentail/assets/images/hero-slide3.png"
type = "image"
title = "teal bg red roses craft"
