import { describe, it, expect, vi, beforeEach } from "vitest";
import express from "express";
import request from "supertest";

// ---------------------------------------------------------------------------
// Route-level tests for POST /api/fb/events (mobile Purchase path)
//
// Verifies the /fb/events adapter that the Expo mobile app calls after a
// successful order creation:
//   - The handler calls sendCapiEvent with the correct parameters for a
//     signed-in shopper (email, phone present) and a guest shopper (no email).
//   - Required fields (event, countryCode) are validated and 400 is returned
//     when they are absent.
//   - The handler responds 200 before the CAPI request settles (fire-and-forget).
//   - The handler uses actionSource: "app" so Facebook attributes these events
//     to the mobile app rather than the web browser.
//
// NOTE: The mobile CAPI path does not send a client-side event_id. The
// eventId used for Facebook server-side deduplication is generated by
// sendCapiEvent() in fbConversions.ts. This test explicitly asserts that no
// eventId is forwarded from the route handler so a schema change would be
// caught here first.
// ---------------------------------------------------------------------------

const { mockSendCapiEvent } = vi.hoisted(() => ({
  mockSendCapiEvent: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("../lib/fbConversions", async (importOriginal) => {
  const original = await importOriginal<typeof import("../lib/fbConversions")>();
  return {
    ...original,
    sendCapiEvent: mockSendCapiEvent,
  };
});

describe("POST /api/fb/events route — mobile Purchase path", () => {
  let app: ReturnType<typeof express>;

  beforeEach(async () => {
    mockSendCapiEvent.mockClear();
    const fbRouter = (await import("./fb")).default;
    app = express();
    app.use(express.json());
    app.use(fbRouter);
  });

  // -------------------------------------------------------------------------
  // Signed-in path — email and phone present
  // -------------------------------------------------------------------------

  it("calls sendCapiEvent with event, countryCode, value, currency, and email for a signed-in shopper", async () => {
    const res = await request(app)
      .post("/fb/events")
      .send({
        event: "Purchase",
        countryCode: "lb",
        value: 85.5,
        currency: "USD",
        contentIds: ["prod-001", "prod-002"],
        email: "jane@example.com",
        phone: "+9611234567",
      });

    expect(res.status).toBe(200);
    expect(res.body).toEqual({ ok: true });
    expect(mockSendCapiEvent).toHaveBeenCalledOnce();

    const callArg = mockSendCapiEvent.mock.calls[0][0] as Record<string, unknown>;
    expect(callArg.eventName).toBe("Purchase");
    expect(callArg.countryCode).toBe("lb");
    expect(callArg.value).toBe(85.5);
    expect(callArg.currency).toBe("USD");
    expect(callArg.contentIds).toEqual(["prod-001", "prod-002"]);
    expect((callArg.userData as Record<string, unknown>)?.email).toBe("jane@example.com");
    expect((callArg.userData as Record<string, unknown>)?.phone).toBe("+9611234567");
  });

  it("uses actionSource 'app' for mobile Purchase events", async () => {
    await request(app)
      .post("/fb/events")
      .send({
        event: "Purchase",
        countryCode: "lb",
        value: 50,
        currency: "USD",
      });

    const callArg = mockSendCapiEvent.mock.calls[0][0] as Record<string, unknown>;
    expect(callArg.actionSource).toBe("app");
  });

  // -------------------------------------------------------------------------
  // Guest path — no email
  // -------------------------------------------------------------------------

  it("calls sendCapiEvent with no email for a guest shopper (Purchase)", async () => {
    const res = await request(app)
      .post("/fb/events")
      .send({
        event: "Purchase",
        countryCode: "lb",
        value: 60,
        currency: "USD",
      });

    expect(res.status).toBe(200);
    expect(res.body).toEqual({ ok: true });
    expect(mockSendCapiEvent).toHaveBeenCalledOnce();

    const callArg = mockSendCapiEvent.mock.calls[0][0] as Record<string, unknown>;
    expect(callArg.eventName).toBe("Purchase");
    expect((callArg.userData as Record<string, unknown>)?.email).toBeUndefined();
  });

  // -------------------------------------------------------------------------
  // No client-side event_id — server generates its own for deduplication
  // -------------------------------------------------------------------------

  it("does not forward a client-supplied eventId — sendCapiEvent generates its own for deduplication", async () => {
    await request(app)
      .post("/fb/events")
      .send({
        event: "Purchase",
        countryCode: "lb",
        value: 50,
        currency: "USD",
        // No eventId in the body — the route must not invent one.
      });

    const callArg = mockSendCapiEvent.mock.calls[0][0] as Record<string, unknown>;
    // When the body omits eventId the forwarded value is undefined so that
    // sendCapiEvent() generates a fresh random ID internally. We assert on the
    // value, not property existence, because optional Zod fields may still
    // appear as undefined keys in the destructured object.
    expect(callArg.eventId).toBeUndefined();
    expect(callArg.event_id).toBeUndefined();
  });

  // -------------------------------------------------------------------------
  // UAE countryCode
  // -------------------------------------------------------------------------

  it("forwards UAE countryCode correctly for Purchase events", async () => {
    const res = await request(app)
      .post("/fb/events")
      .send({
        event: "Purchase",
        countryCode: "ae",
        value: 200,
        currency: "AED",
        email: "shopper@example.ae",
      });

    expect(res.status).toBe(200);
    const callArg = mockSendCapiEvent.mock.calls[0][0] as Record<string, unknown>;
    expect(callArg.countryCode).toBe("ae");
    expect(callArg.currency).toBe("AED");
    expect((callArg.userData as Record<string, unknown>)?.email).toBe("shopper@example.ae");
  });

  // -------------------------------------------------------------------------
  // Input validation
  // -------------------------------------------------------------------------

  it("returns 400 when event field is missing", async () => {
    const res = await request(app)
      .post("/fb/events")
      .send({ countryCode: "lb", value: 50, currency: "USD" });

    expect(res.status).toBe(400);
    expect(res.body.ok).toBe(false);
    expect(mockSendCapiEvent).not.toHaveBeenCalled();
  });

  it("returns 400 when countryCode field is missing", async () => {
    const res = await request(app)
      .post("/fb/events")
      .send({ event: "Purchase", value: 50, currency: "USD" });

    expect(res.status).toBe(400);
    expect(res.body.ok).toBe(false);
    expect(mockSendCapiEvent).not.toHaveBeenCalled();
  });

  it("returns 400 when event is not a recognised Facebook event name", async () => {
    const res = await request(app)
      .post("/fb/events")
      .send({ event: "UnknownEvent", countryCode: "lb", value: 50 });

    expect(res.status).toBe(400);
    expect(res.body.ok).toBe(false);
    expect(mockSendCapiEvent).not.toHaveBeenCalled();
  });

  // -------------------------------------------------------------------------
  // Fire-and-forget — 200 even when CAPI send fails
  // -------------------------------------------------------------------------

  it("responds 200 even when sendCapiEvent rejects (fire-and-forget)", async () => {
    mockSendCapiEvent.mockRejectedValueOnce(new Error("CAPI timeout"));

    const res = await request(app)
      .post("/fb/events")
      .send({
        event: "Purchase",
        countryCode: "lb",
        value: 50,
        currency: "USD",
      });

    expect(res.status).toBe(200);
    expect(res.body).toEqual({ ok: true });
  });
});
