import { Router, type IRouter } from "express";
import healthRouter from "./health";
import checkoutRouter from "./checkout";
import paymentRouter from "./payment";
import wooRouter from "./woo";
import wooSyncRouter from "./wooSync";
import authRouter from "./auth";
import pushRouter from "./push";
import deliveryLocationsRouter from "./delivery-locations";
import catalogRouter from "./catalog";
import deliveryConfigRouter from "./delivery-config";
import fxRouter from "./fx";
import geoRouter from "./geo";
import homepageRouter from "./homepage";
import meRouter from "./me";
import meAddressesRouter from "./meAddresses";
import clientErrorsRouter from "./clientErrors";
import analyticsRouter from "./analytics";
import adminFunnelsRouter from "./adminFunnels";
import adminSeoAuditRouter from "./adminSeoAudit";
import adminImageDimsRouter from "./adminImageDims";
import loyaltyRouter from "./loyalty";
import favoritesRouter from "./favorites";
import osWebhookRouter from "./osWebhook";
import wooWebhookRouter from "./wooWebhook";
import seoRouter from "./seo";

const router: IRouter = Router();

router.use(healthRouter);
router.use(checkoutRouter);
router.use(paymentRouter);
router.use(wooRouter);
router.use(wooSyncRouter);
router.use(authRouter);
router.use(pushRouter);
router.use(deliveryLocationsRouter);
router.use(catalogRouter);
router.use(deliveryConfigRouter);
router.use(fxRouter);
router.use(geoRouter);
router.use(homepageRouter);
router.use(meRouter);
router.use(meAddressesRouter);
router.use(clientErrorsRouter);
router.use(analyticsRouter);
router.use(adminFunnelsRouter);
router.use(adminSeoAuditRouter);
router.use(adminImageDimsRouter);
router.use(loyaltyRouter);
router.use(favoritesRouter);
router.use(osWebhookRouter);
router.use(wooWebhookRouter);
router.use(seoRouter);

export default router;
