/**
 * Blog image performance regression tests (LCP / responsive image guard)
 *
 * The blog hero loading was tuned for Core Web Vitals: the article hero is a
 * responsive, eagerly-fetched, high-priority image that resolves to a sized
 * variant (never the full-resolution original), while the blog-index cards are
 * lazy-loaded with their own responsive srcset. The web-vitals monitor tracks
 * LCP globally, but nothing asserts the blog-specific markup, so a regression
 * (dropping the srcset, removing fetchpriority, or re-introducing a full-res
 * hero) would silently degrade LCP on the editorial pages.
 *
 * These specs run against the production serve.mjs build (the "Web serve
 * checks" workflow) and use a real browser so the React-rendered <img>
 * attributes and the browser's actual srcset candidate selection are exercised
 * — exactly what a shopper's browser sees. They assert:
 *
 *   /blog                — every story card <img> carries the responsive
 *                          srcset (-480 / -768 variants), a sizes hint,
 *                          intrinsic width/height (no layout shift), and is
 *                          lazily decoded.
 *   /blog/<slug>         — the hero <img> is eager + fetchpriority="high",
 *                          carries the responsive srcset + sizes + intrinsic
 *                          dimensions, and the LCP element the browser actually
 *                          paints (currentSrc) resolves to a SIZED variant
 *                          (e.g. -768.webp), never the full-resolution original.
 *   variant files        — the generated -480 / -768 WebP variants are served
 *                          (200 + image/webp), so the srcset descriptors never
 *                          point at missing files.
 *
 * We use the locale-prefixed paths (mirroring structured-data.spec.ts) and a
 * real article slug from the shared @workspace/blog-content source of truth.
 */

import { test, expect } from "@playwright/test";

const BLOG_INDEX = "/en-lb/beirut/blog";
const BLOG_POST = "/en-lb/beirut/blog/inside-spring-sourcing-trip";

// The hero/og image for the article above (see lib/blog-content). Its sized
// variants are pre-generated by the build into public/blog/.
const HERO_BASE = "/blog/inside-spring-sourcing-trip";
const HERO_INTRINSIC = "inside-spring-sourcing-trip.webp";

test.describe("Blog image performance — index cards /en-lb/beirut/blog", () => {
  test("story card images are responsive (srcset + sizes), sized, and lazy", async ({ page }) => {
    await page.goto(BLOG_INDEX, { waitUntil: "domcontentloaded" });

    const cards = page.getByTestId("blog-story-card-image");
    await expect(cards.first()).toBeVisible();

    const count = await cards.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < count; i++) {
      const img = cards.nth(i);

      // Responsive srcset that points at the pre-generated sized variants.
      const srcset = await img.getAttribute("srcset");
      expect(srcset, "story card must declare a responsive srcset").toBeTruthy();
      expect(srcset).toContain("-480.webp 480w");
      expect(srcset).toContain("-768.webp 768w");

      // A sizes hint so the browser can pick the right candidate.
      const sizes = await img.getAttribute("sizes");
      expect(sizes, "story card must declare a sizes hint").toBeTruthy();

      // Intrinsic dimensions prevent cumulative layout shift (CLS).
      expect(await img.getAttribute("width")).toBeTruthy();
      expect(await img.getAttribute("height")).toBeTruthy();

      // Cards are below the hero — they must be lazy so they never compete with
      // the LCP element for bandwidth.
      expect(await img.getAttribute("loading")).toBe("lazy");
      expect(await img.getAttribute("decoding")).toBe("async");
    }
  });
});

test.describe("Blog image performance — article hero /en-lb/beirut/blog/<slug>", () => {
  test("hero image is responsive, eager + high priority, with intrinsic dimensions", async ({ page }) => {
    await page.goto(BLOG_POST, { waitUntil: "domcontentloaded" });

    const hero = page.getByTestId("blog-post-hero-image");
    await expect(hero).toBeVisible();

    // Responsive srcset that includes the sized variant.
    const srcset = await hero.getAttribute("srcset");
    expect(srcset, "hero must declare a responsive srcset").toBeTruthy();
    expect(srcset).toContain("-768.webp 768w");

    // A sizes hint so the browser can pick the right candidate.
    const sizes = await hero.getAttribute("sizes");
    expect(sizes, "hero must declare a sizes hint").toBeTruthy();

    // The hero is the LCP element: it must load eagerly at high priority.
    expect(await hero.getAttribute("loading")).toBe("eager");
    expect((await hero.getAttribute("fetchpriority"))?.toLowerCase()).toBe("high");

    // Intrinsic dimensions prevent cumulative layout shift (CLS).
    expect(await hero.getAttribute("width")).toBeTruthy();
    expect(await hero.getAttribute("height")).toBeTruthy();
  });

  test("the painted LCP hero resolves to a sized variant, not the full-res original", async ({ page }) => {
    await page.goto(BLOG_POST, { waitUntil: "load" });

    const hero = page.getByTestId("blog-post-hero-image");
    await expect(hero).toBeVisible();

    // Wait until the browser has actually committed to a candidate (currentSrc
    // is the resolved URL the browser painted for the LCP element).
    await expect
      .poll(async () => hero.evaluate((el: HTMLImageElement) => el.currentSrc), {
        message: "hero currentSrc never resolved",
      })
      .toMatch(/\/blog\/inside-spring-sourcing-trip-(480|768)\.webp$/);

    // Confirm the image really decoded (non-zero natural size).
    const naturalWidth = await hero.evaluate(
      (el: HTMLImageElement) => el.naturalWidth,
    );
    expect(naturalWidth).toBeGreaterThan(0);

    // Defensive: the painted candidate must NOT be the full-resolution original
    // (a re-introduced full-res hero is exactly the regression we guard.)
    const currentSrc = await hero.evaluate(
      (el: HTMLImageElement) => el.currentSrc,
    );
    expect(currentSrc.endsWith(HERO_INTRINSIC)).toBe(false);
  });
});

test.describe("Blog image performance — generated variant files are served", () => {
  for (const width of [480, 768]) {
    test(`hero ${width}w variant is served as WebP (200)`, async ({ request }) => {
      const response = await request.get(`${HERO_BASE}-${width}.webp`);
      expect(response.status(), `${HERO_BASE}-${width}.webp must exist`).toBe(200);
      expect(response.headers()["content-type"] ?? "").toContain("image/webp");
    });
  }
});
