/**
 * Hero image srcset regression tests
 *
 * Verifies that the occasion page (/occasion/birthday) and the brand detail
 * page (/brand/<slug>) both render a hero <img> element whose `srcset`
 * attribute contains `?w=1200` — the 1200w resize entry generated by
 * `buildCatalogHeroImageSrcset` in `src/lib/imageUtils.ts`.
 *
 * If the resize pipeline ever regresses and the hero falls back to requesting
 * the raw catalog proxy URL (no `?w=` param), these tests will fail.
 *
 * All external calls are stubbed so the tests run without a live API or OS key.
 */

import { test, expect, type Page } from "@playwright/test";

// ---------------------------------------------------------------------------
// Shared stubs
// ---------------------------------------------------------------------------

const DELIVERY_LOCATION = { countryCode: "LB", cityId: "lb-beirut" };

const STUB_CURRENCIES = {
  currencies: [
    {
      code: "USD",
      name: "US Dollar",
      symbol: "$",
      symbolPosition: "left",
      spaceBetween: false,
      decimals: 0,
    },
  ],
  fallbackCode: "USD",
  countryToCurrency: { LB: "USD" },
};

const STUB_FX_RATES = { ok: true, base: "USD", rates: { USD: 1 } };

/**
 * A minimal 1×1 transparent PNG, base64-encoded.
 * Returned for any catalog image proxy request so the ShimmerImage <img>
 * element stays in the DOM (a 404 triggers the `onError` handler which
 * sets `failed=true` and removes the element before we can read srcset).
 */
const TINY_PNG_B64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

/** Seed localStorage delivery location before the first navigation. */
async function seedLocation(page: Page): Promise<void> {
  await page.addInitScript((loc) => {
    window.localStorage.setItem(
      "presentail_delivery_location_v1",
      JSON.stringify(loc),
    );
  }, DELIVERY_LOCATION);
}

/** Common currency / geo stubs required by every page. */
async function stubCurrencyAndGeo(page: Page): Promise<void> {
  await page.route("**/api/currencies", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(STUB_CURRENCIES),
    }),
  );
  await page.route("**/api/fx/rates", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(STUB_FX_RATES),
    }),
  );
  await page.route("**/api/geo/currency", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ countryCode: "LB", currencyCode: "USD" }),
    }),
  );
}

// ---------------------------------------------------------------------------
// 1. Occasion hero — /occasion/birthday
// ---------------------------------------------------------------------------

test.describe("Occasion hero image srcset", () => {
  test.beforeEach(async ({ page }) => {
    await stubCurrencyAndGeo(page);

    // Catalog metadata: occasion "birthday" has a catalog proxy image URI.
    // buildCatalogHeroImageSrcset() recognises this prefix and generates srcset.
    await page.route(/\/api\/catalog\/metadata/, (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({
          categories: [],
          occasions: [
            {
              id: "birthday",
              name: "Birthday",
              icon: "cake",
              image: { uri: "/api/catalog/occasion-image/birthday" },
            },
          ],
          brands: [],
        }),
      }),
    );

    // Products fallback — any product list is fine; the hero renders regardless.
    await page.route("**/api/woo/products**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, products: [] }),
      }),
    );

    // OS direct-fetch path (if VITE_OS_API_KEY is set in the test env).
    await page.route("**/os.presentail.com/api/products**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ products: [], totalPages: 1 }),
      }),
    );

    // Brand allowlist — 404 means no filtering applied.
    await page.route("**/api/catalog/brand-allowlist", (route) =>
      route.fulfill({ status: 404, body: "" }),
    );

    // Stub the catalog image proxy so ShimmerImage's onError never fires.
    // Without this the img element is removed from the DOM before we can read
    // the srcset attribute.
    await page.route("**/api/catalog/occasion-image/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "image/png",
        body: Buffer.from(TINY_PNG_B64, "base64"),
      }),
    );

    await seedLocation(page);
    await page.goto("/en-lb/beirut/occasion/birthday");
  });

  test("hero <img> has a non-empty srcset containing ?w=1200", async ({
    page,
  }) => {
    // Wait for the ShimmerImage wrapper that contains the hero.
    // The banner is rendered inside `div.relative.rounded-2xl.overflow-hidden`.
    const heroBanner = page
      .locator("div.rounded-2xl.overflow-hidden")
      .filter({ has: page.locator('img[srcset*="occasion-image"]') })
      .first();

    await expect(heroBanner).toBeVisible({ timeout: 15_000 });

    const heroImg = heroBanner.locator("img").first();
    await expect(heroImg).toBeAttached({ timeout: 10_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toBeTruthy();
    expect(srcset).toContain("?w=1200");
  });

  test("hero srcset does NOT contain a raw URL without ?w= param", async ({
    page,
  }) => {
    const heroImg = page
      .locator('img[srcset*="occasion-image"]')
      .first();

    await expect(heroImg).toBeAttached({ timeout: 15_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toBeTruthy();

    // Every srcset entry must carry a ?w= resize param. Split on ", " and
    // assert that none of the descriptor strings lacks "?w=".
    const entries = (srcset ?? "").split(",").map((e) => e.trim());
    for (const entry of entries) {
      expect(entry).toContain("?w=");
    }
  });

  test("hero srcset contains the 800w and 1600w entries too", async ({
    page,
  }) => {
    const heroImg = page
      .locator('img[srcset*="occasion-image"]')
      .first();

    await expect(heroImg).toBeAttached({ timeout: 15_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toContain("?w=800");
    expect(srcset).toContain("?w=1600");
  });
});

// ---------------------------------------------------------------------------
// 2. Category hero — /category/<slug>
// ---------------------------------------------------------------------------

test.describe("Category hero image srcset", () => {
  test.beforeEach(async ({ page }) => {
    await stubCurrencyAndGeo(page);

    // Catalog metadata: category "hand-bouquets" has a catalog proxy image URI.
    // buildCatalogHeroImageSrcset() recognises this prefix and generates srcset.
    await page.route(/\/api\/catalog\/metadata/, (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({
          categories: [
            {
              id: "hand-bouquets",
              name: "Hand Bouquets",
              slug: "hand-bouquets",
              image: { uri: "/api/catalog/category-image/hand-bouquets" },
            },
          ],
          occasions: [],
          brands: [],
        }),
      }),
    );

    // Products fallback — any product list is fine; the hero renders regardless.
    await page.route("**/api/woo/products**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, products: [] }),
      }),
    );

    // OS direct-fetch path (if VITE_OS_API_KEY is set in the test env).
    await page.route("**/os.presentail.com/api/products**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ products: [], totalPages: 1 }),
      }),
    );

    // Brand allowlist — 404 means no filtering applied.
    await page.route("**/api/catalog/brand-allowlist", (route) =>
      route.fulfill({ status: 404, body: "" }),
    );

    // Stub the catalog image proxy so ShimmerImage's onError never fires.
    await page.route("**/api/catalog/category-image/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "image/png",
        body: Buffer.from(TINY_PNG_B64, "base64"),
      }),
    );

    await seedLocation(page);
    await page.goto("/en-lb/beirut/category/hand-bouquets");
  });

  test("hero <img> has a non-empty srcset containing ?w=1200", async ({
    page,
  }) => {
    const heroBanner = page
      .locator("div.rounded-2xl.overflow-hidden")
      .filter({ has: page.locator('img[srcset*="category-image"]') })
      .first();

    await expect(heroBanner).toBeVisible({ timeout: 15_000 });

    const heroImg = heroBanner.locator("img").first();
    await expect(heroImg).toBeAttached({ timeout: 10_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toBeTruthy();
    expect(srcset).toContain("?w=1200");
  });

  test("hero srcset does NOT contain a raw URL without ?w= param", async ({
    page,
  }) => {
    const heroImg = page
      .locator('img[srcset*="category-image"]')
      .first();

    await expect(heroImg).toBeAttached({ timeout: 15_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toBeTruthy();

    const entries = (srcset ?? "").split(",").map((e) => e.trim());
    for (const entry of entries) {
      expect(entry).toContain("?w=");
    }
  });

  test("hero srcset contains the 800w and 1600w entries too", async ({
    page,
  }) => {
    const heroImg = page
      .locator('img[srcset*="category-image"]')
      .first();

    await expect(heroImg).toBeAttached({ timeout: 15_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toContain("?w=800");
    expect(srcset).toContain("?w=1600");
  });
});

// ---------------------------------------------------------------------------
// 3. Brand hero — /brand/<slug>
// ---------------------------------------------------------------------------

/**
 * Use a slug that is NOT in BRAND_COVER_IMAGES (hallab-1881, apple,
 * sables-gourmets, salma). When a static cover PNG exists, it takes priority
 * over brand?.image and is a local file — not a catalog proxy URL — so
 * buildCatalogHeroImageSrcset returns null and no srcset is generated.
 * "test-brand" forces the code to fall back to brand?.image which we supply
 * as a catalog proxy URL.
 */
const BRAND_SLUG = "test-brand";

test.describe("Brand hero image srcset", () => {
  test.beforeEach(async ({ page }) => {
    await stubCurrencyAndGeo(page);

    // Brands endpoint — return our test brand with a catalog proxy image URL.
    await page.route("**/api/woo/brands**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({
          ok: true,
          brands: [
            {
              id: BRAND_SLUG,
              name: "Test Brand",
              slug: BRAND_SLUG,
              image: `/api/catalog/brand-image/${BRAND_SLUG}`,
            },
          ],
        }),
      }),
    );

    // Brand products fallback endpoint.
    await page.route("**/api/woo/brand-products**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, products: [], count: 0 }),
      }),
    );

    // OS direct-fetch path.
    await page.route("**/os.presentail.com/api/products**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ products: [], totalPages: 1 }),
      }),
    );

    // Brand allowlist.
    await page.route("**/api/catalog/brand-allowlist", (route) =>
      route.fulfill({ status: 404, body: "" }),
    );

    // Catalog metadata (used by Navbar / search).
    await page.route(/\/api\/catalog\/metadata/, (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ categories: [], occasions: [], brands: [] }),
      }),
    );

    // Stub the catalog brand-image proxy so ShimmerImage stays in the DOM.
    await page.route("**/api/catalog/brand-image/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "image/png",
        body: Buffer.from(TINY_PNG_B64, "base64"),
      }),
    );

    await seedLocation(page);
    await page.goto(`/en-lb/beirut/brand/${BRAND_SLUG}`);
  });

  test("hero <img> has a non-empty srcset containing ?w=1200", async ({
    page,
  }) => {
    // Wait for the brand name heading to confirm the page has rendered.
    await expect(
      page.getByRole("heading", { name: "Test Brand", level: 1 }),
    ).toBeVisible({ timeout: 15_000 });

    const heroImg = page
      .locator('img[srcset*="brand-image"]')
      .first();

    await expect(heroImg).toBeAttached({ timeout: 10_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toBeTruthy();
    expect(srcset).toContain("?w=1200");
  });

  test("hero srcset does NOT contain a raw URL without ?w= param", async ({
    page,
  }) => {
    await expect(
      page.getByRole("heading", { name: "Test Brand", level: 1 }),
    ).toBeVisible({ timeout: 15_000 });

    const heroImg = page
      .locator('img[srcset*="brand-image"]')
      .first();

    await expect(heroImg).toBeAttached({ timeout: 10_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toBeTruthy();

    const entries = (srcset ?? "").split(",").map((e) => e.trim());
    for (const entry of entries) {
      expect(entry).toContain("?w=");
    }
  });

  test("hero srcset contains the 800w and 1600w entries too", async ({
    page,
  }) => {
    await expect(
      page.getByRole("heading", { name: "Test Brand", level: 1 }),
    ).toBeVisible({ timeout: 15_000 });

    const heroImg = page
      .locator('img[srcset*="brand-image"]')
      .first();

    await expect(heroImg).toBeAttached({ timeout: 10_000 });

    const srcset = await heroImg.getAttribute("srcset");
    expect(srcset).toContain("?w=800");
    expect(srcset).toContain("?w=1600");
  });
});
