// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/checkout-redesign/CardAccordion.tsx": () => import("../components/mockups/checkout-redesign/CardAccordion.tsx"),
  "./components/mockups/checkout-redesign/MinimalStepper.tsx": () => import("../components/mockups/checkout-redesign/MinimalStepper.tsx"),
  "./components/mockups/checkout-redesign/SplitPanel.tsx": () => import("../components/mockups/checkout-redesign/SplitPanel.tsx")
};
